### ISSUE TITLE
Update readme.md to support new feature

### ISSUE THREAD

**Issue by mazipan** [mazipan/vue-string-filter#14]
If you see this file https://github.com/mazipan/vue-string-filter/blob/master/VueStringFilter.js, we already support new feature like `remove`, `remove_first`, `replace`, `replace_first`, `append`.

Need to update readme.md to include this new feature

**Comment by JackieCalapristi** [comment]
I can take this one! 😃 

Update: I've opened a PR for this here: https://github.com/mazipan/vue-string-filter/pull/16

**Comment by kshitijpurwar** [comment]
PR opened. @mazipan  Please let me know if the examples given are appropriate.
