### ISSUE TITLE
Add append function

### ISSUE THREAD

**Issue by mazipan** [mazipan/vue-string-filter#2]
See here for `append` sample function

https://help.shopify.com/en/themes/liquid/filters/string-filters#append

**Comment by euclid1990** [comment]
@mazipan 
Can I help you to get hacktoberfest t-shirt =)) 🤣

**Comment by mazipan** [comment]
Sure, this issue is for helping beginner that wanna try to contribute to open source.
Also get your #hacktoberfest count

**Comment by euclid1990** [comment]
@mazipan Okay, let coding now 👍

**Comment by euclid1990** [comment]
PR is up, #9  .
