### ISSUE TITLE
Add replace function

### ISSUE THREAD

**Issue by mazipan** [mazipan/vue-string-filter#4]
See here for function `replace` sample

https://help.shopify.com/en/themes/liquid/filters/string-filters#replace
And 
https://help.shopify.com/en/themes/liquid/filters/string-filters#replace_first

**Comment by rbo13** [comment]
Can I take this issue? Or someones already implementing this one? CC @mazipan

**Comment by hasinifoss** [comment]
I've submitted a PR for this: https://github.com/mazipan/vue-string-filter/pull/5

**Comment by mazipan** [comment]
Already merged, but still need to add Unit testing

**Comment by rbo13** [comment]
Can I create the unit testing for the submitted PR? Or @hasinifoss is creating the unit test? Would love to take the unit test :) CC @mazipan

**Comment by hasinifoss** [comment]
@rbo13 Sure, please go ahead!

**Comment by rbo13** [comment]
It seems the unit test is already added... CC @mazipan @hasinifoss
